version: '3.8'

services:
  ci_system:
    build: .
    ports:
      - "8080:8080"  # For webhook
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # For managing external containers
      - ./logs:/app/logs  # For CI logs
      - ./data:/app/data  # For webhook data

    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock # ENC Variable to tell docker where to find the docker daemon's socket
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=${SMTP_USER}  # Will be taken from host environment
      - SMTP_PASSWORD=${SMTP_PASSWORD}  # Will be taken from host environment
      - SENDER_EMAIL=${SMTP_USER}
      - RECIPIENT_EMAILS=${RECIPIENT_EMAILS}
    restart: always
