services:
  db:
    build: ./sql
    container_name: 'bill-sql'
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD
    networks:
      - my_net
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "bill-sql" ]
      timeout: 10s
      retries: 10
  app:
    build: .
    container_name: 'ci_test_billing'
    ports:
      - 5001:5001
    volumes:
      - ./volumes/in:/app/in
      - ./volumes/out:/app/out
    environment:
      - MYSQL_ROOT_PASSWORD
    networks:
      - my_net
      - test_network
    depends_on:
      db:
        condition: service_healthy

networks:
  my_net:
    driver: bridge
    external: true
  test_network:
    name: ci_test_network
    external: true
