services:
  db:
    build: ./sql
    container_name: 'bill-sql'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD
    networks:
      - my_net
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
  app:
    build: .
    container_name: 'bill-app'
    ports:
      - 5001:5001
    volumes:
      - ./volumes/in:/app/in
      - ./volumes/out:/app/out
    environment:
      - MYSQL_ROOT_PASSWORD
    networks:
      - my_net
    depends_on:
      db:
        condition: service_healthy

networks:
  my_net: