version: '3'
services:
  billing:
    build:
      context: ../Billing-Team
    container_name: prod_billing
    ports:
      - "8082:8082"
    networks:
      - prod_network
    

networks:
  prod_network:
    name: ci_prod_network
    external: true
