version: '3'
services:
  billing:
    build:
      context: .    # Changed from ../Billing-Team
    container_name: ci_prod_billing  # Changed to be consistent with naming
    ports:
      - "8082:8082"
    networks:
      - prod_network
networks:
  prod_network:
    name: ci_prod_network
    external: true
