version: '3'
services:
  weight:
    build: 
      context: ../Weight-Team    # Path to Weight-Team from project root
    container_name: ci_test_weight
    ports:
      - "8081:8081"
    networks:
      - test_network

networks:
  test_network:
    name: ci_test_network
    external: true    # Add this line - tells Docker the network already exists
