version: '3.8'

services:
  # Flask app service
  app:
    build: .
    container_name: weights-trucks-app
    environment:
      - DB_HOST=mysql-db
      - DB_USER=weight_team
      - DB_PASSWORD=12345
      - DB_NAME=truck_weights
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - my_network

  # MySQL database service
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: truck_weights
      MYSQL_USER: weight_team
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./weight_db/weightdb.sql:/docker-entrypoint-initdb.d/weightdb.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  my_network:
    driver: bridge

volumes:
  mysql-data:

